<?xml version="1.0"?>
<robot name="embla" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- IMU -->
	<xacro:property name="imuHeight" value="0.010" />
	<xacro:property name="imuDiameter" value="0.031" />
	<xacro:property name="imuMass" value="0.030" />

	<joint name="imu_joint" type="fixed">
		<parent link="base_link" />
		<child link="imu_link" />
		<!-- Origin is at center of IMU which is placed on chassis top, a little back from midpoint -->
		<origin xyz="-0.05 0 ${chassisHeight/2 + imuHeight/2}" rpy="0 0 ${PI/2}" />
	</joint>

	<link name="imu_link">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder length="${imuHeight}" radius="${imuDiameter/2}" />
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder length="${imuHeight}" radius="${imuDiameter/2}" />
			</geometry>
			<material name="orange" />
		</visual>
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="${imuMass}" />
			<xacro:cylinder_inertia m="${imuMass}" r="${imuDiameter/2}" h="${imuHeight}" />
		</inertial>
	</link>

	<gazebo reference="imu_link">
		<material>Gazebo/Orange</material>
	</gazebo>

	<!-- Team Hector's IMU plugin https://github.com/tu-darmstadt-ros-pkg/hector_gazebo -->
	<gazebo>
		<plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
			<robotNamespace>/</robotNamespace>
			<updateRate>50.0</updateRate>
			<bodyName>imu_link</bodyName>
			<topicName>imu/data</topicName>
			<accelDrift>0.005 0.005 0.005</accelDrift>
			<accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
			<rateDrift>0.005 0.005 0.005 </rateDrift>
			<rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
			<headingDrift>0.005</headingDrift>
			<headingGaussianNoise>0.005</headingGaussianNoise>
		</plugin>
	</gazebo>

</robot>