<?xml version="1.0"?>
<robot name="embla" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Macro for wheels.
	Parameters:
	     - lr: use "left" or "right" to specify side. This must match the value of the tY parameter.
	     - fr: use "front" or "rear" to specify front/rear. This must match the value of the tX parameter.
	     - tY: Y coordinate multiplier. Use 1 for lr=left and -1 for lr=right
	     - tX: X coordinate multiplier. Use 1 for fr=front and -1 for fr=rear
	-->
	<xacro:macro name="wheel" params="lr fr tY tX">
		<joint name="${lr}_${fr}_wheel_joint" type="continuous">
			<parent link="base_link" />
			<child link="${lr}_${fr}_wheel" />
			<origin
				xyz="${tX * wheelXDistance/2} ${tY * wheelYDistance/2} ${-chassisHeight/2 - (chassisGroundClearance - wheelRadius)}" />
			<axis xyz="0 1 0" rpy="0 0 0" />
			<limit effort="100" velocity="100" />
			<joint_properties damping="0.0" friction="0.5" />
		</joint>

		<link name="${lr}_${fr}_wheel">
			<collision>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheelWidth}" radius="${wheelRadius}" />
				</geometry>
				<surface>
					<friction>
						<ode>
							<mu>200</mu>
							<mu2>100</mu2>
						</ode>
					</friction>
				</surface>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheelWidth}" radius="${wheelRadius}" />
				</geometry>
				<material name="black" />
			</visual>

			<inertial>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
				<mass value="${wheelMass}" />
				<xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}" />
			</inertial>
		</link>

		<!-- Gazebo sim -->
		<gazebo reference="${lr}_${fr}_wheel">
			<material>Gazebo/FlatBlack</material>
			<mu1>100000000000000.0</mu1>
			<mu2>1000000000.0</mu2>
			<kp>1000000000000.0</kp>
			<kd>10.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>0.1</maxVel>
			<fdir1>1 0 0</fdir1>
		</gazebo>

		<transmission name="${lr}_${fr}_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${lr}_${fr}_wheel_joint" role="joint_${lr}_${fr}">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</joint>
			<actuator name="${lr}_${fr}_motor" role="actuator_${lr}_${fr}" />
		</transmission>
	</xacro:macro>
</robot>